// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/glennprays/golang-clean-arch-starter/config"
	"github.com/glennprays/golang-clean-arch-starter/internal/handler"
	"github.com/glennprays/golang-clean-arch-starter/internal/router"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	routerRouter := router.NewRouter(healthHandler)
	app := &App{
		Config:        configConfig,
		HealthHandler: healthHandler,
		Router:        routerRouter,
	}
	return app, nil
}
