// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/glennprays/golang-clean-arch-starter/internal/config"
	"github.com/glennprays/golang-clean-arch-starter/internal/handler"
)

// InitializeApp creates a new App with all dependencies wired up.
func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	app := &App{
		Config:        configConfig,
		HealthHandler: healthHandler,
	}
	return app, nil
}
